{% set name = "bluesky" %}
{% set version = "1.14.1" %}

package:
  name: {{ name|lower }}-suite
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 72dc8d69982fa3bf49eca496a9b5b121cfc080df9ef505a475e488159e29021d

build:
  number: 0

# to avoid creating redundant CI jobs, conda-smithy needs python
# to be used in all outputs, including the implicit global one.
requirements:
  host:
    - python


outputs:
  - name: bluesky-base
    build:
      noarch: python
      script: python -m pip install . --no-deps -vv
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
      run:
        - python >={{ python_min }}
        - cycler
        - event-model >=1.14.0
        - historydict
        - msgpack-numpy
        - msgpack-python
        - numpy
        - opentelemetry-api
        - toolz
        - tqdm >=4.44
        - zict
    test:
      imports:
        - bluesky

  - name: bluesky
    build:
      noarch: python
    requirements:
      host:
        - {{ pin_subpackage('bluesky-base', max_pin="x.x.x") }}
      run:
        - databroker
        - doct
        - ipython
        - lmfit
        - matplotlib
        - ophyd
        - pyzmq
        - {{ pin_subpackage('bluesky-base', max_pin="x.x.x") }}
    test:
      imports:
        - bluesky
        - bluesky.plans
        - bluesky.callbacks
      commands:
        - pip check
      requires:
        - pip


about:
  home: https://blueskyproject.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python data collection interface for experimental science
  description: A Python data collection interface for experimental science
  doc_url: https://blueskyproject.io/bluesky
  dev_url: https://github.com/bluesky/bluesky

extra:
  recipe-maintainers:
    - conda-forge/event-model
