appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: U5taKnc0UIBfD7up4qro4Xw4Q85PoQIhw5WIKDO81dcDZ7rT0WcYjWE+OFNYQbq8K3I6gvlU74dl6d3rMiqTuCUFCpxa1aFokeKofr+aSE2If+ujI7W4SAjjIl3DogGqkpWtttSpkAWoQfDMSIcUQbGmnouEA/XNv4N5ynQN5TQfDBiFvnwbK18gkFkJO1OphQku/GPKIwQBdd5LdxjxHg+rZWV8R+ISZdvqP6eYk8pBkr7XAVvKKucDXn8TvaYz/Qd6K0wAmSlmDuXfOth8Jw7dHYmAhPsbRxcc20NSvRn8Tnj4QklNqVnqeXMfZH2pxFi770FLOICMEwrdon/mQfBPeC19NWP8VWrzLED4TeNXkM8Tmr99S0abZQhApGWplo5PTlh8fK6zSBRU288fkVoy41pgS4ABWXiN+syRqQmc4P0T/Io81OHfbJ+Q1RvXGmpeH0x0M96NJPudL6iU6lXySJwjqxHLcMGWcgtvyrZSI6Mg7niljthbTWDLgN6dLgxc3mYfiIUBUV+MFwEz/mnkPQeo/S3Ml2eCoQRrXnZ95+Qwi09Rjwe8LVa5XvZH06og/XOoF5+fYR6Z6IZSO7viM9VxL5IyOOF8Hpl/9TwZk1RfDcRqttv6vfrKCcoWaFiBMN8mfrnVmC3inDiQ6nAG2FDDIhYQKaox5iEauZQ=}
provider:
  win: azure
conda_forge_output_validation: true
